version: '3.8'

services:
  keycloak:
    image: keycloak/keycloak:26.0.1-0
    container_name: antonio3a-keycloak-TEST
    hostname: keycloak.antonio3a.aaa
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgresql.antonio3a.aaa:5432/antonio3a_keycloak
      - KC_DB_USERNAME=${AAA_USER}
      - KC_DB_PASSWORD=${AAA_PASS}
      - KEYCLOAK_ADMIN=${AAA_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${AAA_PASS}
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - antonio3a-network
    restart: always
    command: [
      "/opt/keycloak/bin/kc.sh",
      "start-dev",
      "--features=token-exchange",
    ]
    deploy:
      resources:
        limits:
          memory: 1G

networks:
  antonio3a-network:
    external: true
