version: '3.8'

x-common: &common
  networks:
    - antonio3a-network
  restart: unless-stopped

services:
  elasticsearch:
    <<: *common
    image: elasticsearch:${ELASTIC_VERSION}
    container_name: antonio3a-elasticsearch
    hostname: elasticsearch.antonio3a.aaa
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - antonio3a-elasticsearch-data-vol:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 1G

  logstash:
    <<: *common
    image: logstash:${ELASTIC_VERSION}
    container_name: antonio3a-logstash
    hostname: logstash.antonio3a.aaa
    volumes:
      - ${AAA_HOME}/logstash/pipeline:/usr/share/logstash/pipeline
      - ${AAA_HOME}/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    ports:
      - "5000:5000"
      - "9600:9600"
    depends_on:
      - elasticsearch

  kibana:
    <<: *common
    image: kibana:${ELASTIC_VERSION}
    container_name: antonio3a-kibana
    hostname: kibana.antonio3a.aaa
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch.antonio3a.aaa:9200
    ports:
      - "5701:5601"
    depends_on:
      - elasticsearch

networks:
  antonio3a-network:
    external: true

volumes:
  antonio3a-elasticsearch-data-vol:
    external: true