x-common: &common
  networks:
    - antonio3a-bridge
  restart: unless-stopped

services:
  elasticsearch:
    <<: *common
    image: elasticsearch:${ELASTIC_VERSION}
    container_name: antonio3a-elasticsearch
    hostname: elasticsearch.antonio3a.aaa
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - antonio3a-elasticsearch-data-vol:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 1G

  logstash:
    <<: *common
    image: logstash:${ELASTIC_VERSION}
    container_name: antonio3a-logstash
    hostname: logstash.antonio3a.aaa
    volumes:
      - ${AAA_HOME}/logstash/pipeline:/usr/share/logstash/pipeline
      - ${AAA_HOME}/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    ports:
      - "5000:5000"
      - "9600:9600"
    depends_on:
        elasticsearch:
          condition: service_started

  kibana:
    <<: *common
    image: kibana:${ELASTIC_VERSION}
    container_name: antonio3a-kibana
    hostname: kibana.antonio3a.aaa
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch.antonio3a.aaa:9200
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_started

  apm-server:
    <<: *common
    image: elastic/apm-server:${ELASTIC_VERSION}
    container_name: antonio3a-apm-server
    hostname: apm-server.antonio3a.aaa
    volumes:
      - ${AAA_HOME}/apm-server/apm-server.yml:/usr/share/apm-server/apm-server.yml
    ports:
      - "8201:8200"
    depends_on:
      elasticsearch:
        condition: service_started
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    command: >
      apm-server -e
         -E output.elasticsearch.hosts=["elasticsearch.antonio3a.aaa:9200"]
         -E output.elasticsearch.protocol=http
#         -E output.elasticsearch.username=elastic
#         -E output.elasticsearch.password=${ELASTIC_PASSWORD}
#         -E output.elasticsearch.ssl.enabled=true
#         -E output.elasticsearch.ssl.certificate_authorities=/usr/share/apm-server/certs/ca/ca.crt
#         -E output.elasticsearch.ssl.certificate=/usr/share/apm-server/certs/es01/es01.crt
#         -E output.elasticsearch.ssl.key=/usr/share/apm-server/certs/es01/es01.key

networks:
  antonio3a-bridge:
    external: true

volumes:
  antonio3a-elasticsearch-data-vol:
    external: true