version: '3.8'

services:
  kafka:
    image: bitnami/kafka:3.7.0
    container_name: antonio3a-kafka
    hostname: kafka.antonio3a.aaa
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka.antonio3a.aaa:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka.antonio3a.aaa:9092,EXTERNAL://kafka.antonio3a.aaa:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    ports:
      - "9092:9092"
      - "9094:9094"
    volumes:
      - antonio3a-kafka-vol:/bitnami/kafka
    networks:
      - antonio3a-net
    restart: unless-stopped

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: antonio3a-kafka-ui
    hostname: kafka-ui.antonio3a.aaa
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
    ports:
      - "8280:8080"
    networks:
      - antonio3a-net
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.13.4-management
    container_name: antonio3a-rabbitmq
    hostname: rabbitmq.antonio3a.aaa
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - antonio3a-net
    environment:
      RABBITMQ_DEFAULT_USER: ${AAA_USER}
      RABBITMQ_DEFAULT_PASS: ${AAA_PASS}
    volumes:
      - antonio3a-rabbitmq-vol:/var/lib/rabbitmq
      - ${AAA_HOME}/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins

networks:
  antonio3a-net:
    external: true

volumes:
  antonio3a-kafka-vol:
    external: true
  antonio3a-rabbitmq-vol:
    external: true
