version: '3'

services:
  opentelemetry-collector:
    image: otel/opentelemetry-collector-contrib:0.105.0
    container_name: devops-opentelemetry-collector
    hostname: opentelemetry-collector.devops.cpdi
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus' metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension
    volumes:
      - /home/devops/opentelemetry-collector/otel-collector.yml:/etc/otelcol-contrib/otel-collector.yml
    networks:
      - devops-network
    restart: unless-stopped
    command:
      - --config=/etc/otelcol-contrib/otel-collector.yml

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.59.0
    container_name: devops-jaeger
    hostname: jaeger.devops.cpdi
    environment:
        #- COLLECTOR_ZIPKIN_HTTP_PORT=9411
        - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "4317"
    networks:
      - devops-network
    restart: unless-stopped

networks:
  devops-network:
    external: true

volumes:
  antonio3a-minio-data-vol:
    external: true
