version: '3.8'

services:
  minio:
    image: minio/minio:RELEASE.2024-06-22T05-26-45Z
    container_name: antonio3a-minio
    hostname: minio.antonio3a.aaa
    environment:
      - MINIO_ROOT_USER=${AAA_USER}
      - MINIO_ROOT_PASSWORD=${AAA_PASS}
    ports:
      - "9100:9000"
      - "9101:9001"
    volumes:
      - antonio3a-minio-vol:/data
    networks:
      - antonio3a-network
    restart: unless-stopped
    command: server /data --console-address ":9001"

networks:
  antonio3a-network:
    external: true

volumes:
  antonio3a-minio-vol:
    external: true
