version: '3.8'

x-common-top: &common-top
  image: registry.antonio3a.aaa/aaa/common/discovery-service
  networks:
    - antonio3a-network
  restart: always

x-common-env: &common-env
  VAULT_URI: ${VAULT_URI}
  VAULT_TOKEN: ${VAULT_TOKEN}
  EUREKA_ENVIRONMENT: development
  EUREKA_CLIENT_FETCH-REGISTRY: true
  EUREKA_CLIENT_REGISTER-WITH-EUREKA: true

services:
  antonio3a-discovery-service-1:
    <<: *common-top
    container_name: antonio3a-discovery-service-1
    hostname: discovery1.antonio3a.aaa
    environment:
      <<: *common-env
      SERVER_PORT: 8761
      SPRING_PROFILES_ACTIVE: peer1
      EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE: http://discovery2.antonio3a.aaa:8762/eureka/,http://discovery3.antonio3a.aaa:8763/eureka/
    ports:
      - "8761:8761"

  antonio3a-discovery-service-2:
    <<: *common-top
    container_name: antonio3a-discovery-service-2
    hostname: discovery2.antonio3a.aaa
    environment:
      <<: *common-env
      SERVER_PORT: 8762
      SPRING_PROFILES_ACTIVE: peer2
      EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE: http://discovery1.antonio3a.aaa:8761/eureka/,http://discovery3.antonio3a.aaa:8763/eureka/
    ports:
      - "8762:8762"

  antonio3a-discovery-service-3:
    <<: *common-top
    container_name: antonio3a-discovery-service-3
    hostname: discovery3.antonio3a.aaa
    environment:
      <<: *common-env
      SERVER_PORT: 8763
      SPRING_PROFILES_ACTIVE: peer3
      EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE: http://discovery1.antonio3a.aaa:8761/eureka/,http://discovery2.antonio3a.aaa:8762/eureka/
    ports:
      - "8763:8763"

networks:
  antonio3a-network:
    external: true
