version: '3.8'

services:
  gitlab:
    image: gitlab/gitlab-ee:17.1.2-ee.0
    container_name: antonio3a-gitlab
    hostname: gitlab.antonio3a.aaa
    ports:
      - "22:22"
      - "80:80"
      - "443:443"
    volumes:
      - antonio3a-gitlab-data-vol:/var/opt/gitlab
      - antonio3a-gitlab-config-vol:/etc/gitlab
      - antonio3a-gitlab-logs-vol:/var/log/gitlab
      - ${AAA_HOME}/ssl:/etc/gitlab/ssl
    networks:
      - antonio3a-net
    restart: unless-stopped
    #gitlab-rake "gitlab:password:reset[root]"

networks:
  antonio3a-net:
    external: true

volumes:
  antonio3a-gitlab-data-vol:
    external: true
  antonio3a-gitlab-config-vol:
    external: true
  antonio3a-gitlab-logs-vol:
    external: true