x-common : &common
  networks:
    - antonio3a-network
  restart: unless-stopped

services:
  grafana:
    <<: *common
    image: grafana/grafana:11.2.2
    container_name: antonio3a-grafana
    hostname: grafana.antonio3a.aaa
    ports:
      - "3000:3000"
    volumes:
      - antonio3a-grafana-vol:/var/lib/grafana

  loki:
    <<: *common
    image: grafana/loki:3.2.1
    container_name: antonio3a-loki
    hostname: loki.antonio3a.aaa
    ports:
      - "3100:3100"
    volumes:
      - antonio3a-grafana-loki-vol:/loki

  tempo:
    <<: *common
    image: grafana/tempo:2.6.1
    container_name: antonio3a-tempo
    hostname: tempo.antonio3a.aaa
    ports:
      - "3200:3200"
      - "9511:9411"
    volumes:
      - ${AAA_HOME}/tempo/tempo.yaml:/etc/tempo.yaml
      - antonio3a-grafana-tempo-vol:/var/lib/tempo
    command: [ "-config.file=/etc/tempo.yaml" ]

networks:
  antonio3a-network:
    external: true

volumes:
  antonio3a-grafana-vol:
    external: true
  antonio3a-grafana-loki-vol:
    external: true
  antonio3a-grafana-tempo-vol:
    external: true