x-common: &common
  networks:
    - antonio3a-bridge
  restart: unless-stopped

services:
  gitlab:
    <<: *common
    image: gitlab/gitlab-ee:17.5.0-ee.0
    container_name: antonio3a-gitlab
    hostname: gitlab.antonio3a.aaa
    ports:
      - "22:22"
      - "80:80"
      - "443:443"
    volumes:
      - antonio3a-gitlab-data-vol:/var/opt/gitlab
      - antonio3a-gitlab-config-vol:/etc/gitlab
      - antonio3a-gitlab-logs-vol:/var/log/gitlab
      - ${AAA_HOME}/ssl:/etc/gitlab/ssl
    #gitlab-rake "gitlab:password:reset[root]"

  gitlab-runner:
    <<: *common
    image: gitlab/gitlab-runner:v17.5.0
    container_name: antonio3a-gitlab-runner
    hostname: gitlab-runner.antonio3a.aaa
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - antonio3a-gitlab-runner-config-vol:/etc/gitlab-runner

  sonarqube:
    <<: *common
    image: sonarqube:10.7.0-community
    container_name: antonio3a-sonarqube
    hostname: sonarqube.antonio3a.aaa
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://antonio3a-postgresql/antonio3a_sonarqube_db
      - SONAR_JDBC_USERNAME=${AAA_USER}
      - SONAR_JDBC_PASSWORD=${AAA_PASS}
    ports:
      - "9400:9000"
    volumes:
      - antonio3a-sonarqube-data-vol:/opt/sonarqube/data
      - antonio3a-sonarqube-logs-vol:/opt/sonarqube/logs
      - antonio3a-sonarqube-extensions-vol:/opt/sonarqube/extensions

  jenkins:
    <<: *common
    image: jenkins/jenkins:2.481-jdk21
    container_name: antonio3a-jenkins
    hostname: jenkins.antonio3a.aaa
    ports:
      - "8180:8080"
      - "50000:50000"
    volumes:
      - antonio3a-jenkins-vol:/var/jenkins_home

networks:
  antonio3a-bridge:
    external: true

volumes:
  antonio3a-gitlab-data-vol:
    external: true
  antonio3a-gitlab-config-vol:
    external: true
  antonio3a-gitlab-logs-vol:
    external: true
  antonio3a-gitlab-runner-config-vol:
    external: true
  antonio3a-sonarqube-data-vol:
    external: true
  antonio3a-sonarqube-logs-vol:
    external: true
  antonio3a-sonarqube-extensions-vol:
    external: true
  antonio3a-jenkins-vol:
    external: true