version: '3.8'

services:
  zipkin:
    image: openzipkin/zipkin:3.4.0
    container_name: antonio3a-zipkin
    hostname: zipkin.antonio3a.aaa
    ports:
      - "9411:9411"
    networks:
      - antonio3a-net
    restart: unless-stopped

networks:
  antonio3a-net:
    external: true
