x-common: &common
  networks:
    - antonio3a-bridge
  restart: unless-stopped

services:
  elasticsearch:
    <<: *common
    image: elasticsearch:${ELASTIC_VERSION}
    container_name: antonio3a-elasticsearch
    hostname: elasticsearch.antonio3a.aaa
    environment:
      - node.name=antonio3a-es0
      - cluster.name=antonio3a-es-cluster
      #- cluster.initial_master_nodes=antonio3a-es#
      - discovery.type=single-node
      #- discovery.seed_hosts=antonio3a-es[1-n]
      - ELASTIC_PASSWORD=${AAA_PASS}
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/antonio3a.aaa.key
      - xpack.security.http.ssl.certificate=certs/antonio3a.aaa.crt
      - xpack.security.http.ssl.certificate_authorities=certs/antonio3a-ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/antonio3a.aaa.key
      - xpack.security.transport.ssl.certificate=certs/antonio3a.aaa.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/antonio3a-ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ${AAA_HOME}/ssl/certs/antonio3a:/usr/share/elasticsearch/config/certs
      - antonio3a-elasticsearch-data-vol:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 1G

  logstash:
    <<: *common
    image: logstash:${ELASTIC_VERSION}
    container_name: antonio3a-logstash
    hostname: logstash.antonio3a.aaa
    volumes:
      - ${AAA_HOME}/logstash/pipeline:/usr/share/logstash/pipeline
      - ${AAA_HOME}/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ${AAA_HOME}/ssl/certs/antonio3a:/usr/share/logstash/config/certs
    ports:
      - "5000:5000"
      - "9600:9600"
    depends_on:
        elasticsearch:
          condition: service_started

  kibana:
    <<: *common
    image: kibana:${ELASTIC_VERSION}
    container_name: antonio3a-kibana
    hostname: kibana.antonio3a.aaa
    environment:
      - SERVERNAME=antonio3a-kibana
      - ELASTICSEARCH_HOSTS=https://elasticsearch.antonio3a.aaa:9200
      - ELASTICSEARCH_SERVICEACCOUNTTOKEN=token
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=/usr/share/kibana/config/certs/antonio3a-ca.crt
      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_KEY=/usr/share/kibana/config/certs/antonio3a.aaa.key
      - SERVER_SSL_CERTIFICATE=/usr/share/kibana/config/certs/antonio3a.aaa.crt
      - SERVER_SSL_CERTIFICATEAUTHORITIES=/usr/share/kibana/config/certs/antonio3a-ca.crt
      - XPACK_SECURITY_ENCRYPTIONKEY=${ENCRYPTION_KEY}
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${ENCRYPTION_KEY}
      - XPACK_REPORTING_ENCRYPTIONKEY=${ENCRYPTION_KEY}
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_started
    volumes:
      - ${AAA_HOME}/ssl/certs/antonio3a:/usr/share/kibana/config/certs
      - antonio3a-kibana-data-vol:/usr/share/kibana/data

  apm-server:
    <<: *common
    image: elastic/apm-server:${ELASTIC_VERSION}
    container_name: antonio3a-apm-server
    hostname: apm-server.antonio3a.aaa
    volumes:
      - ${AAA_HOME}/apm-server/apm-server.yml:/usr/share/apm-server/apm-server.yml
    ports:
      - "8201:8200"
    depends_on:
      elasticsearch:
        condition: service_started
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    command: >
      apm-server -e
         -E output.elasticsearch.hosts=["elasticsearch.antonio3a.aaa:9200"]
         -E output.elasticsearch.protocol=http
#         -E output.elasticsearch.username=elastic
#         -E output.elasticsearch.password=${ELASTIC_PASSWORD}
#         -E output.elasticsearch.ssl.enabled=true
#         -E output.elasticsearch.ssl.certificate_authorities=/usr/share/apm-server/certs/ca/ca.crt
#         -E output.elasticsearch.ssl.certificate=/usr/share/apm-server/certs/es01/es01.crt
#         -E output.elasticsearch.ssl.key=/usr/share/apm-server/certs/es01/es01.key

networks:
  antonio3a-bridge:
    external: true

volumes:
  antonio3a-elasticsearch-data-vol:
  antonio3a-kibana-data-vol: