network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: false
      addresses:
        - 172.16.33.56/18
      routes:
        - to: default
          via: 172.16.63.254
      nameservers:
        addresses:
          - 1.1.1.1
          - 172.16.63.254
          - 8.8.8.8