global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: /metrics
    static_configs:
      - targets:
          - localhost:9090

  - job_name: node-exporter
    static_configs:
      - targets: ['cpdi-devops-main:9110']
  - job_name: docker
    static_configs:
      - targets: ["cpdi-devops-main:9323"]

  - job_name: "micro-services"
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /actuator/prometheus
    eureka_sd_configs:
      - server: http://eureka1.devops.cpdi:8761/eureka
        refresh_interval: 3s
      - server: http://eureka2.devops.cpdi:8761/eureka
        refresh_interval: 3s
      - server: http://eureka3.devops.cpdi:8761/eureka
        refresh_interval: 3s
    relabel_configs:
      - source_labels: [ __meta_eureka_app_name ]
        target_label: application
      - source_labels: [ __meta_eureka_app_instance_id ]
        target_label: instance
